# These are supported funding model platforms

github: zhouxiaoka
# patreon: # Create a new page at https://www.patreon.com/yourpage
# open_collective: # Create a new page at https://opencollective.com/yourpage
# ko_fi: # Create a new page at https://ko-fi.com/yourpage
# tidelift: # Create a new page at https://tidelift.com/funding/github/yourpage
# community_bridge: # Create a new page at https://funding.communitybridge.org/yourpage
# liberapay: # Create a new page at https://liberapay.com/yourpage
# issuehunt: # Create a new page at https://issuehunt.io/r/yourpage
# otechie: # Create a new page at https://otechie.com/yourpage
# custom: # Create a new page at https://yourpage.com 